version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: supermarketdb
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: netcore-app
    ports:
      - "5151:8080"
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=supermarketdb;User=rootuser;Password=rootpassword;
    restart: always

volumes:
  mysql_data: